---
engines:
  radon:
    enabled: true
    config:
      python_version: 3
    exclude_fingerprints:
    - dd8b0c981429d84e570ecf65b5b26927
  rubocop:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- node_modules/**/*
